-- Crypto Signal AI Supabase schema
-- Run this in Supabase SQL Editor.

create table if not exists users (
    id bigint generated by default as identity primary key,
    telegram_id text unique not null,
    signals_enabled boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists signals (
    id bigint generated by default as identity primary key,
    telegram_id text not null,
    symbol text not null,
    side text not null,
    entry_low numeric not null,
    entry_high numeric not null,
    stop_loss numeric not null,
    tp1 numeric not null,
    tp2 numeric not null,
    tp3 numeric not null,
    leverage integer not null,
    max_hold_minutes integer not null,
    confidence integer,
    risk_score integer,
    status text not null default 'open',
    exit_price numeric,
    close_note text,
    expires_at timestamptz,
    closed_at timestamptz,
    raw jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_signals_telegram_status
on signals (telegram_id, status);

create index if not exists idx_signals_symbol_status
on signals (symbol, status);

create index if not exists idx_signals_created
on signals (created_at desc);
